
var questions = [
{
    id: "A1",
    question: " I funghi:",
    options: ["A contengono clorofilla", "B non contengono clorofilla", "C hanno tutti l’anello"],
    answer: 1,
    explanation: "B non contengono clorofilla",
},
{
    id: "A2",
    question: " I funghi appartengono:",
    options: ["A al regno vegetale", "B al regno animale", "C ad un regno a sé stante"],
    answer: 2,
    explanation: "C ad un regno a sé stante",
},
{
    id: "A3",
    question: " Al regno dei funghi appartengono:",
    options: ["A solo quelli ben visibili ad occhio nudo", "B quelli che hanno il cappello", "C anche quelli microscopici non visibili ad occhio nudo"],
    answer: 2,
    explanation: "C anche quelli microscopici non visibili ad occhio nudo",
},
{
    id: "A4",
    question: " Cos’è il micelio:",
    options: ["A la parte riproduttiva del fungo", "B la parte vegetativa del fungo", "C è costituito da spore"],
    answer: 1,
    explanation: "B la parte vegetativa del fungo",
},
{
    id: "A5",
    question: " I funghi epigei sono:",
    options: ["A quelli che non hanno il gambo", "B quelli che crescono sopra il suolo", "C tutti quelli che hanno l’anello"],
    answer: 1,
    explanation: "B quelli che crescono sopra il suolo",
},
{
    id: "A6",
    question: " I funghi ipogei:",
    options: ["A non esistono", "B crescono solo in America", "C sono quelli che crescono sotto il suolo"],
    answer: 2,
    explanation: "C sono quelli che crescono sotto il suolo",
},
{
    id: "A7",
    question: " I funghi:",
    options: ["A si autoalimentano come le piante", "B non sono in grado di costruirsi le sostanze nutritizie", "C vivono negli ambienti acquatici"],
    answer: 1,
    explanation: "B non sono in grado di costruirsi le sostanze nutritizie",
},
{
    id: "A8",
    question: " I funghi si riproducono:",
    options: ["A per mezzo di semi chiamati “spore”", "B solo a luna calante", "C per duplicazione come i batteri"],
    answer: 0,
    explanation: "A per mezzo di semi chiamati “spore”",
},
{
    id: "A9",
    question: " I funghi che crescono su vegetali viventi sono definiti:",
    options: ["A parassiti", "B saprofiti", "C simbionti"],
    answer: 0,
    explanation: "A parassiti",
},
{
    id: "A10",
    question: "I funghi che crescono su sostanza organica morta sono definiti:",
    options: ["A parassiti", "B saprofiti", "C simbionti"],
    answer: 1,
    explanation: "B saprofiti",
},
{
    id: "A11",
    question: "I funghi che vivono in unione con piante sono definiti:",
    options: ["A parassiti", "B saprofiti", "C simbionti"],
    answer: 2,
    explanation: "C simbionti",
},
{
    id: "A12",
    question: "I funghi definiti spontanei:",
    options: ["A non esistono", "B sono tutti quelli che si possono vendere", "C sono quelli che provengono dall’ambiente naturale"],
    answer: 2,
    explanation: "C sono quelli che provengono dall’ambiente naturale",
},
{
    id: "A13",
    question: "I funghi definiti freschi:",
    options: ["A sono solo quelli spontanei", "B sono quelli che non sono stati sottoposti a trattamenti di conservazione", "C sono solo quelli coltivati"],
    answer: 1,
    explanation: "B sono quelli che non sono stati sottoposti a trattamenti di conservazione",
},
{
    id: "A14",
    question: "I funghi freschi spontanei:",
    options: ["A non provengono da coltivazioni", "B sono quelli naturali", "C sono quelli coltivati nei Paesi dell’est Europa"],
    answer: 0,
    explanation: "A non provengono da coltivazioni",
},
{
    id: "A15",
    question: "I funghi sono:",
    options: ["A frutti di una propria “pianta” generalmente non visibile", "B pianticelle con proprie radici", "C vegetali incompleti"],
    answer: 0,
    explanation: "A frutti di una propria “pianta” generalmente non visibile",
},
{
    id: "A16",
    question: "I funghi che si coltivano:",
    options: ["A sono solo i porcini e gli champignon", "B si allevano su piante", "C appartengono al gruppo dei funghi saprofiti"],
    answer: 2,
    explanation: "C appartengono al gruppo dei funghi saprofiti",
},
{
    id: "A17",
    question: "I semi contenuti nei funghi:",
    options: ["A sono pochissimi", "B sono definiti “spore”", "C sono assenti nei funghi coltivati"],
    answer: 1,
    explanation: "B sono definiti “spore”",
},
{
    id: "A18",
    question: "La parte del fungo dove ci sono le spore:",
    options: ["A sacchetto", "B vescicola", "C imenio"],
    answer: 2,
    explanation: "C imenio",
},
{
    id: "A19",
    question: "Nei funghi che hanno il cappello, le spore si trovano:",
    options: ["A sotto il cappello", "B nella carne", "C sopra il gambo"],
    answer: 0,
    explanation: "A sotto il cappello",
},
{
    id: "A20",
    question: "I funghi che hanno le lamelle:",
    options: ["A sono molto rari", "B non appartengono al gruppo dei porcini", "C crescono solo in montagna"],
    answer: 1,
    explanation: "B non appartengono al gruppo dei porcini",
},
{
    id: "A21",
    question: "I funghi con lamelle:",
    options: ["A sono pericolosi", "B crescono solo in pianura", "C sono i più diffusi"],
    answer: 2,
    explanation: "C sono i più diffusi",
},
{
    id: "A22",
    question: "I funghi sotto il cappello:",
    options: ["A possono avere anche dei tubicini", "B hanno sempre un anello", "C sono sempre di colore bianco"],
    answer: 0,
    explanation: "A possono avere anche dei tubicini",
},
{
    id: "A23",
    question: "L’anello nei funghi:",
    options: ["A distingue quelli buoni da quelli cattivi", "B è sempre presente", "C è caratteristico solo di alcune specie"],
    answer: 2,
    explanation: "C è caratteristico solo di alcune specie",
},
{
    id: "A24",
    question: "L’anello dei funghi:",
    options: ["A non serve a distinguere i funghi mangerecci da quelli tossici", "B è posseduto solo da alcune specie di porcini", "C non cade mai"],
    answer: 0,
    explanation: "A non serve a distinguere i funghi mangerecci da quelli tossici",
},
{
    id: "A25",
    question: "La volva:",
    options: ["A è tipica dei porcini di importazione", "B ce l’hanno tutti i funghi coltivati", "C è tipica di alcuni funghi lamellati"],
    answer: 2,
    explanation: "C è tipica di alcuni funghi lamellati",
},
{
    id: "A26",
    question: "La volva è:",
    options: ["A un insetto ospite dei funghi", "B sempre presente nelle Amanita", "C una malformazione di alcune specie di funghi"],
    answer: 1,
    explanation: "B sempre presente nelle Amanita",
},
{
    id: "A27",
    question: "La volva:",
    options: ["A ce l’hanno solo i funghi pregiati", "B non esiste nei funghi", "C è il residuo di un velo che protegge lo sviluppo di taluni funghi"],
    answer: 2,
    explanation: "C è il residuo di un velo che protegge lo sviluppo di taluni funghi",
},
{
    id: "A28",
    question: "Il gambo nei funghi:",
    options: ["A è sempre di colore bianco", "B non esiste nei funghi ipogei", "C è il tronco della pianta fungo"],
    answer: 1,
    explanation: "B non esiste nei funghi ipogei",
},
{
    id: "A29",
    question: "La conformazione del gambo:",
    options: ["A è un utile elemento nella determinazione dei funghi", "B non è significativa", "C è la parte del fungo che contiene i grassi"],
    answer: 0,
    explanation: "A è un utile elemento nella determinazione dei funghi",
},
{
    id: "A30",
    question: "In alcune specie di funghi sul gambo vi può essere:",
    options: ["A l’anello", "B la lamellula", "C la vitamina C"],
    answer: 0,
    explanation: "A l’anello",
},
{
    id: "A31",
    question: "Il colore dei funghi:",
    options: ["A è molto importante per il riconoscimento", "B non è molto significativo per il riconoscimento", "C è dovuto alla clorofilla contenuta"],
    answer: 0,
    explanation: "A è molto importante per il riconoscimento",
},
{
    id: "A32",
    question: "I funghi con colori vivaci:",
    options: ["A sono tutti velenosi", "B vengono colorati artificialmente", "C sono ricchi di coloranti naturali"],
    answer: 2,
    explanation: "C sono ricchi di coloranti naturali",
},
{
    id: "A33",
    question: "La carne dei funghi:",
    options: ["A è molto ricca di proteine nobili", "B può essere di diverso colore", "C è sempre bianca"],
    answer: 1,
    explanation: "B può essere di diverso colore",
},
{
    id: "A34",
    question: "Se la carne di alcuni funghi cambia di colore all’aria:",
    options: ["A vuol dire che si tratta di funghi velenosi", "B vuol significare che i funghi sono alterati", "C è una caratteristica di alcune specie fungine"],
    answer: 2,
    explanation: "C è una caratteristica di alcune specie fungine",
},
{
    id: "A35",
    question: "L’odore dei funghi:",
    options: ["A è molto significativo per la loro identificazione", "B è sempre assente nei funghi buoni da mangiare", "C è disgustoso nei funghi con le lamelle"],
    answer: 0,
    explanation: "A è molto significativo per la loro identificazione",
},
{
    id: "A36",
    question: "La commestibilità dei funghi:",
    options: ["A viene decisa dal Governo", "B è stabilita dallo Stato", "C è il risultato di ripetuti consumi da parte del genere umano"],
    answer: 2,
    explanation: "C è il risultato di ripetuti consumi da parte del genere umano",
},
{
    id: "A37",
    question: "Il gambo:",
    options: ["A è un elemento che possiedono tutti i funghi", "B può essere assente in certe specie fungine", "C è sempre presente nei funghi buoni da mangiare"],
    answer: 1,
    explanation: "B può essere assente in certe specie fungine",
},
{
    id: "A38",
    question: "Il riconoscimento dei funghi si basa:",
    options: ["A sullo studio dei suoi caratteri", "B sull’esperienza del raccoglitore", "C sul confronto con raffigurazioni"],
    answer: 0,
    explanation: "A sullo studio dei suoi caratteri",
},
{
    id: "A39",
    question: "I “semi” dei funghi si chiamano:",
    options: ["A semini", "B spore", "C drupe"],
    answer: 1,
    explanation: "B spore",
},
{
    id: "A40",
    question: "Il nome della “pianta” che produce i funghi è:",
    options: ["A pianta nascosta", "B muffa grigia", "C micelio"],
    answer: 2,
    explanation: "C micelio",
},
{
    id: "A41",
    question: "I funghi hanno “semi”:",
    options: ["A ben visibili ad occhio nudo", "B posti sopra il cappello", "C microscopici o difficili da vedere ad occhio nudo"],
    answer: 2,
    explanation: "C microscopici o difficili da vedere ad occhio nudo",
},
{
    id: "A42",
    question: "Per riconoscere i funghi:",
    options: ["A bisogna guardare se hanno l’anello", "B si devono conoscere le loro caratteristiche", "C basta consultare internet"],
    answer: 1,
    explanation: "B si devono conoscere le loro caratteristiche",
},
{
    id: "A43",
    question: "I funghi freschi:",
    options: ["A si alterano facilmente", "B hanno una conservabilità di sole tre settimane", "C vanno conservati solo nei sacchetti di plastica trasparente"],
    answer: 0,
    explanation: "A si alterano facilmente",
},
{
    id: "A44",
    question: "I funghi freschi:",
    options: ["A vanno conservati al caldo", "B scadono dopo poche settimane", "C si devono conservare in luoghi freschi meglio se a 2°C"],
    answer: 2,
    explanation: "C si devono conservare in luoghi freschi meglio se a 2°C",
},
{
    id: "A45",
    question: "I funghi coltivati:",
    options: ["A provengono esclusivamente dall’estero", "B vengono coltivati solo in particolari grotte", "C possono essere coltivati anche in appositi stabilimenti"],
    answer: 2,
    explanation: "C possono essere coltivati anche in appositi stabilimenti",
},
{
    id: "A46",
    question: "I funghi coltivati:",
    options: ["A si differenziano dagli analoghi spontanei per i colori più vivaci", "B hanno le stesse caratteristiche morfobotaniche degli analoghi spontanei", "C hanno colori sbiaditi perché coltivati al buio"],
    answer: 1,
    explanation: "B hanno le stesse caratteristiche morfobotaniche degli analoghi spontanei",
},
{
    id: "A47",
    question: "Il fungo coltivato più diffuso in Italia è:",
    options: ["A il Boletus edulis o porcino", "B l’Armillaria mellea o chiodino", "C l’Agaricus bisporus o champignon"],
    answer: 2,
    explanation: "C l’Agaricus bisporus o champignon",
},
{
    id: "A48",
    question: "Il nome scientifico del “piopparello” o “pioppino” è:",
    options: ["A Armillaria mellea", "B Pholiota nameko", "C Ciclocybe (Agrocybe) aegerita"],
    answer: 2,
    explanation: "C Ciclocybe (Agrocybe) aegerita",
},
{
    id: "A49",
    question: "Il gelone è una specie fungina:",
    options: ["A che non cresce spontaneamente nell’ambiente", "B è scientificamente denominata “Pleurotus ostreatus”", "C è simbionte dei platani"],
    answer: 1,
    explanation: "B è scientificamente denominata “Pleurotus ostreatus”",
},
{
    id: "A50",
    question: "I porcini di coltivazione:",
    options: ["A hanno il cappello biancastro", "B provengono dalla Sicilia", "C non esistono"],
    answer: 2,
    explanation: "C non esistono",
},
{
    id: "A51",
    question: "I funghi definiti coltivati:",
    options: ["A sono quelli di importazione", "B sono tutti quelli che si possono vendere", "C sono quelli che provengono dalle coltivazioni"],
    answer: 2,
    explanation: "C sono quelli che provengono dalle coltivazioni",
},
{
    id: "A52",
    question: "L'anello:",
    options: ["A è una caratteristica di tutti i funghi magerecci", "B ce l'hanno solo i funghi velenosi", "C è il residuo di un velo che proteggeva la parte fertile del fungo"],
    answer: 2,
    explanation: "C è il residuo di un velo che proteggeva la parte fertile del fungo",
},
{
    id: "A53",
    question: "I funghi buoni da mangiare:",
    options: ["A Hanno la carne bianca", "B Hanno sempre un anello", "C appartengono a specie di comprovata commesibilità"],
    answer: 2,
    explanation: "C appartengono a specie di comprovata commesibilità",
},
{
    id: "A54",
    question: "Quali delle seguenti specie funghine è intensamente coltivata",
    options: ["A Boletus edulis", "B Agaricus bisporus", "C Amanita caesarea"],
    answer: 1,
    explanation: "B Agaricus bisporus",
},
{
  id: "B1",
  question: " I funghi definiti tossici:",
  options: ["A si riconoscono dall’odore sgradevole", "B si riconoscono dai colori sgargianti", "C possono avere anche sapori gradevoli"],
  answer: 2,
  explanation: "C possono avere anche sapori gradevoli",
},
{
  id: "B2",
  question: " I funghi che hanno l’anello:",
  options: ["A sono tutti buoni da mangiare", "B si possono consumare solo se sono giovani", "C comprendono anche specie mortali"],
  answer: 2,
  explanation: "C comprendono anche specie mortali",
},
{
  id: "B3",
  question: " I funghi mortali/velenosi:",
  options: ["A possono essere confusi con specie commestibili", "B si possono consumare solo se sono giovani", "C sono coloratissimi"],
  answer: 0,
  explanation: "A possono essere confusi con specie commestibili",
},
{
  id: "B4",
  question: " I funghi definiti commestibili si possono consumare perché:",
  options: ["A hanno tutti la carne bianca", "B hanno sempre un buon profumo", "C appartengono a specie mangerecce"],
  answer: 2,
  explanation: "C appartengono a specie mangerecce",
},
{
  id: "B5",
  question: " I funghi considerati non commestibili:",
  options: ["A sono quelli velenosi solo da crudi", "B non sono velenosi ma non sono adatti al consumo umano", "C possono provocare anche gravi disturbi intestinali"],
  answer: 1,
  explanation: "B non sono velenosi ma non sono adatti al consumo umano",
},
{
  id: "B6",
  question: " I funghi considerati commestibili:",
  options: ["A vanno consumati solo da crudo", "B si possono consumare solo quando sono completamente sviluppati", "C in alcuni casi possono essere tossici se consumati crudi"],
  answer: 2,
  explanation: "C in alcuni casi possono essere tossici se consumati crudi",
},
{
  id: "B7",
  question: " I funghi considerati commestibili:",
  options: ["A diventano generalmente tali solo dopo la loro cottura", "B appartengono tutti al genere Amanita", "C hanno i tubicini al posto delle lamelle"],
  answer: 0,
  explanation: "A diventano generalmente tali solo dopo la loro cottura",
},
{
  id: "B8",
  question: " I funghi diventano tossici:",
  options: ["A se sono cresciuti in ambienti insalubri", "B quando si tratta di specie commestibili ma alterate", "C se sono cresciuti vicino a funghi velenosi"],
  answer: 1,
  explanation: "B quando si tratta di specie commestibili ma alterate",
},
{
  id: "B9",
  question: " Nelle Marche i funghi tossici:",
  options: ["A non crescono", "B non hanno mai rappresentato un pericolo per la salute umana", "C sono comunemente presenti nell’ambiente"],
  answer: 2,
  explanation: "C sono comunemente presenti nell’ambiente",
},
{
  id: "B10",
  question: "I funghi mortali possono manifestare i sintomi:",
  options: ["A immediatamente dopo il loro consumo", "B anche dopo alcuni giorni dal consumo", "C durante il pasto"],
  answer: 1,
  explanation: "B anche dopo alcuni giorni dal consumo",
},
{
  id: "B11",
  question: "I funghi tossici manifestano i sintomi di intossicazione:",
  options: ["A normalmente entro 5/6 ore dal consumo", "B con estrema violenza durante il loro consumo", "C anche se si annusano"],
  answer: 0,
  explanation: "A normalmente entro 5/6 ore dal consumo",
},
{
  id: "B12",
  question: "I funghi mortali si possono trovare:",
  options: ["A solo in alta montagna", "B anche frammischiati agli ovoli di Amanita caesarea", "C solo sui litorali marini"],
  answer: 1,
  explanation: "B anche frammischiati agli ovoli di Amanita caesarea",
},
{
  id: "B13",
  question: "L’Amanita phalloides è un fungo:",
  options: ["A mortale se consumato sia crudo che cotto", "B mortale solo se consumato crudo", "C mortale anche per contatto con la pelle"],
  answer: 0,
  explanation: "A mortale se consumato sia crudo che cotto",
},
{
  id: "B14",
  question: "La cottura prolungata dei funghi tossici e mortali:",
  options: ["A disattiva i veleni contenuti", "B rende commestibili anche i funghi mortali", "C non ne modifica assolutamente la tossicità"],
  answer: 2,
  explanation: "C non ne modifica assolutamente la tossicità",
},
{
  id: "B15",
  question: "L’Amanita phalloides è un fungo che presenta sempre:",
  options: ["A puntini bianchi sul cappello di colore rosso", "B la volva e l’anello", "C un odore di uova marce"],
  answer: 1,
  explanation: "B la volva e l’anello",
},
{
  id: "B16",
  question: "L’Amanita phalloides:",
  options: ["A cresce sui tronchi delle piante vive", "B può essere confusa con funghi commestibili", "C cresce sui tronchi assieme ai chiodini"],
  answer: 1,
  explanation: "B può essere confusa con funghi commestibili",
},
{
  id: "B17",
  question: "L’Amanita phalloides ha il cappello di tipico colore:",
  options: ["A rosso", "B marrone", "C verde olivastro"],
  answer: 2,
  explanation: "C verde olivastro",
},
{
  id: "B18",
  question: "L’Amanita phalloides ha il gambo, le lamelle e la carne di colore:",
  options: ["A bianco", "B giallo", "C rossastro"],
  answer: 0,
  explanation: "A bianco",
},
{
  id: "B19",
  question: "Al genere Amanita appartengono:",
  options: ["A solo funghi tossici o mortali", "B solo funghi commestibili", "C anche specie pregiate commercializzabili"],
  answer: 2,
  explanation: "C anche specie pregiate commercializzabili",
},
{
  id: "B20",
  question: "L’Amanita muscaria è un fungo:",
  options: ["A commestibile", "B mortale", "C tossico e a cappello rosso con i puntini bianchi"],
  answer: 2,
  explanation: "C tossico e a cappello rosso con i puntini bianchi",
},
{
  id: "B21",
  question: "Il fungo mortale più diffuso è:",
  options: ["A il Rubroboletus satanas", "B l’Amanita pantherina", "C l’Amanita phalloides"],
  answer: 2,
  explanation: "C l’Amanita phalloides",
},
{
  id: "B22",
  question: "L’Amanita phalloides nel primo stadio di crescita:",
  options: ["A si può confondere con l’ovolo di Amanita caesarea", "B è di colore rosso", "C ha una evidente volva"],
  answer: 0,
  explanation: "A si può confondere con l’ovolo di Amanita caesarea",
},
{
  id: "B23",
  question: "I veleni contenuti nei funghi definiti tossici:",
  options: ["A sono pericolosi solo se i funghi vengono consumati", "B sono pericolosi anche toccando i funghi", "C non rappresentano alcun pericolo se si toccano i funghi con i guanti"],
  answer: 0,
  explanation: "A sono pericolosi solo se i funghi vengono consumati",
},
{
  id: "B24",
  question: "Gli avvelenamenti da funghi possono dipendere:",
  options: ["A dall’andamento stagionale di crescita", "B anche dal consumo di funghi commestibili ma alterati", "C dai lunghi periodi di siccità"],
  answer: 1,
  explanation: "B anche dal consumo di funghi commestibili ma alterati",
},
{
  id: "B25",
  question: " Se i funghi sono stati raccolti vicino a stracci bagnati o ferri arrugginiti:",
  options: ["A diventano tossici anche se appartengono a specie mangerecce", "B sono pericolosi solo se appartengono a specie tossiche", "C sono ricchi di microrganismi patogeni"],
  answer: 1,
  explanation: "B sono pericolosi solo se appartengono a specie tossiche",
},
{
  id: "B26",
  question: " I funghi tossici quando vengono cotti assieme a funghi mangerecci:",
  options: ["A anneriscono l’argento", "B rendono più brillante la pentola", "C procurano avvelenamenti in chi li consuma"],
  answer: 2,
  explanation: "C procurano avvelenamenti in chi li consuma",
},
{
  id: "B27",
  question: " Per essere sicuri che i funghi cotti sono buoni da mangiare bisogna:",
  options: ["A farli assaggiare al cane o al gatto", "B verificare che in cottura non anneriscano l’aglio", "C essere certi che si tratti di specie mangerecce"],
  answer: 2,
  explanation: "C essere certi che si tratti di specie mangerecce",
},
{
  id: "B28",
  question: " Se sorgono disturbi dopo il consumo di funghi è necessario:",
  options: ["A recarsi presto al pronto soccorso", "B prendere una camomilla e aspettare se passano", "C bere molto latte intero tiepido"],
  answer: 0,
  explanation: "A recarsi presto al pronto soccorso",
},
{
  id: "B29",
  question: " Gli avvelenamenti provocati dal consumo di funghi:",
  options: ["A sono rarissimi in Italia", "B possono essere causati anche da disattenzioni nella fase di vendita", "C non hanno mai riguardato i funghi commercializzati"],
  answer: 1,
  explanation: "B possono essere causati anche da disattenzioni nella fase di vendita",
},
{
  id: "B30",
  question: " Non ci si avvelena con i funghi che si vendono:",
  options: ["A se si beve subito del latte crudo di capra dopo il loro consumo", "B se si è ben sicuri di ciò che si pone in vendita", "C se durante l’esposizione per la vendita non si manifestano cattivi odori"],
  answer: 1,
  explanation: "B se si è ben sicuri di ciò che si pone in vendita",
},
{
  id: "B31",
  question: "I funghi del genere Hypholoma (cosiddetti “falsi chiodini”):",
  options: ["A non sono tossici", "B non hanno le lamelle", "C sono tossici e non hanno le lamelle bianche"],
  answer: 2,
  explanation: "C sono tossici e non hanno le lamelle bianche",
},
{
  id: "B32",
  question: "Il Rubroboletus satanas:",
  options: ["A è un fungo con le lamelle violacee", "B è un fungo tossico confondibile con i porcini", "C è ottimo se consumato poco cotto"],
  answer: 1,
  explanation: "B è un fungo tossico confondibile con i porcini",
},
{
  id: "B33",
  question: "L’Omphalotus olearius:",
  options: ["A è un fungo tossico confondibile con il Cantharellus cibarius", "B è il miglior fungo commestibile degli ulivi", "C si riconosce perché è molto ricco di olio"],
  answer: 0,
  explanation: "A è un fungo tossico confondibile con il Cantharellus cibarius",
},
{
  id: "B34",
  question: "I funghi facilmente confondibili con i Cantharellus:",
  options: ["A hanno i tubuli sotto il cappello", "B non hanno mai delle venature o costolature al posto delle lamelle", "C non hanno colori giallastri"],
  answer: 1,
  explanation: "B non hanno mai delle venature o costolature al posto delle lamelle",
},
{
  id: "B35",
  question: "I funghi tossici o mortali:",
  options: ["A possono essere venduti solo in farmacia", "B hanno proprietà anticancerogene", "C devono essere assolutamente evitati"],
  answer: 2,
  explanation: "C devono essere assolutamente evitati",
},
{
  id: "B36",
  question: "Il metodo più semplice per evitare la presenza di funghi tossici o mortali fra quelli in vendita:",
  options: ["A è quello di essere sicuri della loro assenza", "B consiste nell’osservare il cambiamento del loro colore", "C consiste nell’annusarli spesso"],
  answer: 0,
  explanation: "A è quello di essere sicuri della loro assenza",
},
{
  id: "B37",
  question: "Fra i più comuni funghi mortali vi sono:",
  options: ["A Il Suilellis luridus ed il Rubroboletus satanas", "B L’Hypholoma fasciculare e l’Hydnum repandum", "C Il Cortunarius orellanus e l’Amanita phalloides"],
  answer: 2,
  explanation: "C Il Cortunarius orellanus e l’Amanita phalloides",
},
{
  id: "B38",
  question: "L’odore di acido fenico (inchiostro) è un carattere presente nei funghi?",
  options: ["A si, nei prataioli tossici del gruppo Xanthoderma", "B no", "C si, in esemplari molto maturi"],
  answer: 0,
  explanation: "A si, nei prataioli tossici del gruppo Xanthoderma",
},
{
  id: "B39",
  question: "Il Cortinarius orellanus:",
  options: ["A ha il cappello e lamelle bruno-rossiccio, gambo più chiaro, carne ocracea con odore debole rafanoide", "B ha tubuli e pori rosso-aranciati", "C ha cappello, lamelle e gambo bianchi"],
  answer: 0,
  explanation: "A ha il cappello e lamelle bruno-rossiccio, gambo più chiaro, carne ocracea con odore debole rafanoide",
},
{
  id: "B40",
  question: "La Galerina marginata ha:",
  options: ["A cappello di grandi dimensioni, ocraceo, senza odore e sapore", "B cappello di piccole dimensioni bruno-ocra scuro, carne con sapore di farina, crescita su legni di conifere", "C cappello carnoso, giallo, carne senza odore, crescita sul terreno"],
  answer: 1,
  explanation: "B cappello di piccole dimensioni bruno-ocra scuro, carne con sapore di farina, crescita su legni di conifere",
},
{
  id: "B41",
  question: "La Gyromitra esculenta ha:",
  options: ["A cappello (mitra) conico, bruno-olivastro, carne senza odore, crescita autunnale", "B cappello a forma di sella, gambo cavo, carne biancastra, odore gradevole, crescita autunnale", "C cappello (mitra) simile a un cervello, bruno-rossiccio, gambo cavo biancastro, carne con odore spermatico, crescita primaverile"],
  answer: 2,
  explanation: "C cappello (mitra) simile a un cervello, bruno-rossiccio, gambo cavo biancastro, carne con odore spermatico, crescita primaverile",
},
{
  id: "B42",
  question: "Agaricus xanthodermus:",
  options: ["A ha la carne bianca con odore di mandorle", "B ha la carne bianca virante al giallo su tutte le superfici esterne e più intensamente alla base del gambo dove presenta anche un forte", "odore di inchiostro", "C ha la carne bianca virante al rosso con odore trascurabile"],
  answer: 1,
  explanation: "B ha la carne bianca virante al giallo su tutte le superfici esterne e più intensamente alla base del gambo dove presenta anche un forte odore di inchiostro",
},
{
  id: "B43",
  question: "Entoloma sinuatum:",
  options: ["A è un fungo tossico responsabile di sindrome gastroenterica", "B è un fungo commestibile dopo perfetta cottura", "C è un fungo commestibile"],
  answer: 0,
  explanation: "A è un fungo tossico responsabile di sindrome gastroenterica",
},
{
  id: "B44",
  question: " Entoloma sinuatum:",
  options: ["A ha le lamelle gialle che con la maturazione delle spore diventano rosa, carne con odore e sapore di farina", "B ha le lamelle biancastre sia nel fungo giovane che nell’adulto, carne con odore di farina", "C ha le lamelle biancastre sia nel fungo giovane che adulto, carne con odore e sapore di ravanello"],
  answer: 0,
  explanation: "A ha le lamelle gialle che con la maturazione delle spore diventano rosa, carne con odore e sapore di farina",
},
{
  id: "B45",
  question: " Lactarius piperatus:",
  options: ["A presenta lattice aranciato, carne spessa e compatta, sapore mite", "B presenta lattice bianco immutabile, carne dura e compatta, sapore molto acre", "C presenta lattice bianco che vira al giallo, carne spessa e soda, sapore amaro"],
  answer: 1,
  explanation: "B presenta lattice bianco immutabile, carne dura e compatta, sapore molto acre",
},
{
  id: "B46",
  question: " Sono tutte non commestibili:",
  options: ["A le Russule con sapore piccante o pepato", "B le Russule con lamelle bianche e lardose", "C le Russule con sapore mite"],
  answer: 0,
  explanation: "A le Russule con sapore piccante o pepato",
},
{
  id: "B47",
  question: " Ramaria formosa:",
  options: ["A presenta il tronco bianco e i rami gialli", "B presenta il tronco bianco, i rami rosa salmone, le punte dei rami gialle", "C presenta il tronco e i rami biancastri"],
  answer: 1,
  explanation: "B presenta il tronco bianco, i rami rosa salmone, le punte dei rami gialle",
},
{
  id: "B48",
  question: " Ramaria formosa:",
  options: ["A è un fungo commestibile", "B è un fungo non commestibile", "C è un fungo tossico responsabile di sindrome gastroenterica"],
  answer: 2,
  explanation: "C è un fungo tossico responsabile di sindrome gastroenterica",
},
{
  id: "B49",
  question: " Lepiota helveola:",
  options: ["A è un fungo commestibile", "B è un fungo non commestibile", "C è un fungo velenoso mortale"],
  answer: 2,
  explanation: "C è un fungo velenoso mortale",
},
{
  id: "B50",
  question: "Tricholoma equestre:",
  options: ["A è responsabile di intossicazioni mortali con sindrome rabdomiolitica a seguito di pasti abbondanti e ripetuti", "B è un fungo commestibile", "C è un fungo non commestibile"],
  answer: 0,
  explanation: "A è responsabile di intossicazioni mortali con sindrome rabdomiolitica a seguito di pasti abbondanti e ripetuti",
},
{
  id: "B51",
  question: " Clitocybe dealbata:",
  options: ["A è un fungo tossico", "B è un fungo commestibile", "C è un fungo non commestibile"],
  answer: 0,
  explanation: "A è un fungo tossico",
},
{
  id: "B52",
  question: "Clitocybe dealbata e suo gruppo:",
  options: ["A presenta cappello, lamelle e gambo bianchi", "B presenta cappello bianco, lamelle rosate, gambo fibrilloso", "C presenta cappello, lamelle e gambo gialli"],
  answer: 0,
  explanation: "A presenta cappello, lamelle e gambo bianchi",
},
{
  id: "B53",
  question: "Rubroboletus lupinus:",
  options: ["A ha reticolo sul gambo", "B non ha reticolo sul gambo", "C ha costolature sul gambo"],
  answer: 1,
  explanation: "B non ha reticolo sul gambo",
},
{
  id: "B54",
  question: " Amanita pantherina:",
  options: ["A presenta volva e anello", "B presenta volva", "C presenta anello"],
  answer: 0,
  explanation: "A presenta volva e anello",
},
{
  id: "B55",
  question: " Amanita muscaria:",
  options: ["A ha la volva membranosa", "B non ha la volva", "C ha la volva dissociata"],
  answer: 2,
  explanation: "C ha la volva dissociata",
},
{
  id: "B56",
  question: " Hebeloma sinapizans ha:",
  options: ["A carne dolce e odore fungino", "B carne acre con odore di terriccio", "C carne amara con odore rafanoide"],
  answer: 2,
  explanation: "C carne amara con odore rafanoide",
},
{
  id: "B57",
  question: " Le Amanite phalloides, verna e virosa presentano:",
  options: ["A volva alla base del gambo", "B colori vivaci", "C lamelle ocra"],
  answer: 0,
  explanation: "A volva alla base del gambo",
},
{
  id: "B58",
  question: "L’ambiente di crescita di Galerina marginata è:",
  options: ["A prati perenni", "B boschi di latifoglie", "C legno marcescente di conifere"],
  answer: 1,
  explanation: "B boschi di latifoglie",
},
{
  id: "B59",
  question: " I funghi del genere Cortinarius li possiamo trovare in:",
  options: ["A boschi di conifere e latifoglie", "B prati perenni", "C in prossimità di pascoli"],
  answer: 2,
  explanation: "C in prossimità di pascoli",
},
{
  id: "B60",
  question: " I funghi del genere Lepiota si contraddistinguono per:",
  options: ["A dimensioni ridotte", "B portamento slanciato", "C odore fetido e ripugnante"],
  answer: 0,
  explanation: "A dimensioni ridotte",
},
{
  id: "B61",
  question: " I funghi del genere Gyromitra possono essere confusi con:",
  options: ["A Morchelle", "B Geastrum", "C Helvella"],
  answer: 0,
  explanation: "A Morchelle",
},
{
  id: "B62",
  question: " I funghi del genere Entoloma presentano le lamelle di colore:",
  options: ["A rosato", "B chiaro", "C nere"],
  answer: 0,
  explanation: "A rosato",
},
{
  id: "B63",
  question: " L’imenio dell’Omphalotus olearius si presenta con:",
  options: ["A lamelle", "B lamellule", "C pseudolamelle"],
  answer: 0,
  explanation: "A lamelle",
},
{
  id: "B64",
  question: " L’Hypholoma fasciculare si distingue per il sapore:",
  options: ["A dolce", "B amaro", "C acre"],
  answer: 0,
  explanation: "A dolce",
},
{
  id: "B65",
  question: " Lepiota cristata:",
  options: ["A è un fungo di taglia grande", "B è un fungo di piccola taglia", "C è un fungo di taglia media"],
  answer: 1,
  explanation: "B è un fungo di piccola taglia",
},
{
  id: "B66",
  question: " Mycena pura presenta:",
  options: ["A margine del cappello striato, odore di ravanello", "B margine del cappello sottile, odore agliaceo", "C margine del cappello involuto, odore di farina"],
  answer: 1,
  explanation: "B margine del cappello sottile, odore agliaceo",
},
{
  id: "B67",
  question: " Paxillus involutus ha:",
  options: ["A lamelle fitte, decorrenti sul gambo che si macchiano di bruno al tocco", "B lamelle spaziate", "C lamelle fitte"],
  answer: 0,
  explanation: "A lamelle fitte, decorrenti sul gambo che si macchiano di bruno al tocco",
},
{
  id: "B68",
  question: " Tricholoma pardinum ha:",
  options: ["A cappello fibrilloso giallo verde", "B cappello grigio topo ricoperto da placche squamose su fondo chiaro", "C cappello fibrilloso bruno rossiccio"],
  answer: 1,
  explanation: "B cappello grigio topo ricoperto da placche squamose su fondo chiaro",
},
{
  id: "B69",
  question: " Tricholoma bresadolanum ha:",
  options: ["A cappello olivastrto, gambo liscio, sapore mite", "B cappello giallastro, gambo fibrilloso, sapore farinoso", "C cappello grigio, gambo con squamette scure, sapore amaro e acre"],
  answer: 2,
  explanation: "C cappello grigio, gambo con squamette scure, sapore amaro e acre",
},
{
  id: "B70",
  question: " Inocybe fastigiata presenta:",
  options: ["A cappello umbonato, fibrillato, carne bianca con odore spermatico", "B cappello convesso fibrillato, carne giallastra con odore di farina fresca", "C cappello umbonato, fibrillato, carne bianca con odore di farina rancida"],
  answer: 0,
  explanation: "A cappello umbonato, fibrillato, carne bianca con odore spermatico",
},
{
  id: "B71",
  question: " Agaricus bresadolanus presenta:",
  options: ["A gambo bianco con base bulbillosa", "B ife rizomorfe bianche al fondo del gambo", "C gambo radicante"],
  answer: 1,
  explanation: "B ife rizomorfe bianche al fondo del gambo",
},
{
  id: "B72",
  question: "I funghi tossici sono quelli che:",
  options: ["A causano problemi alla salute alle persone che li consumano", "B appartengono tutti alla famiglia dei satanici", "C emettono veleni gassosi"],
  answer: 0,
  explanation: "A causano problemi alla salute alle persone che li consumano",
},
{
  id: "B73",
  question: "I funghi tossici, di norma:",
  options: ["A determinano avvelenamenti non ad esito mortale", "B provocano la morte immediata del paziende", "C non richiedono cure"],
  answer: 0,
  explanation: "A determinano avvelenamenti non ad esito mortale",
},
{
  id: "B74",
  question: " I funghi tossici più facilmente confondibili con l’Armillaria mellea:",
  options: ["A  hanno i tubuli al posto delle lamelle", "B secernono lattice alla frattura del gambo", "C sono i funghi del genere Hypholoma cosiddetti “falsi chiodini”"],
  answer: 2,
  explanation: "C sono i funghi del genere Hypholoma cosiddetti “falsi chiodini”",
},
{
  id: "B75",
  question: " Russula luteotacta:",
  options: ["A presenta cappello rosso-arancio, lamelle gialle, carne con sapore mite", "B presenta cappello verde, lamelle e gambo bianchi, carne con sapore mite", "C presenta cappello rosso vivo spesso decolorato in bianco o rosa, lamelle e gambo bianchi che si macchiano di giallo, carne bianca con sapore bruciante"],
  answer: 2,
  explanation: "C presenta cappello rosso vivo spesso decolorato in bianco o rosa, lamelle e gambo bianchi che si macchiano di giallo, carne bianca con sapore bruciante",
},
{
  id: "B76",
  question: " L’Amanita phalloides var. alba sulla cuticola del cappello presenta:",
  options: ["A fibrille giallo olivastre", "B colorazione bianca", "C pliche scure"],
  answer: 1,
  explanation: "B colorazione bianca",
},
{
  id: "B77",
  question: "Tricholoma sulphureum presenta:",
  options: ["A cappello, lamelle, gambo e carne di colore giallo zolfo con odore di zolfo", "B cappello, lamelle, gambo e carne di colore bianco con odore di zolfo", "C cappello, lamelle, gambo e carne di colore grigio con odore di farina rancida "],
  answer: 0,
  explanation: "A cappello, lamelle, gambo e carne di colore giallo zolfo con odore di zolfo",
},
{
  id: "C1",
  question: " Le Morchelle si possono confondere con:",
  options: ["A. la Gyromitra esculenta", "B. la Galerina marginata", "C. la Lepiota helveola"],
  answer: 0,
  explanation: "A. la Gyromitra esculenta",
},
{
  id: "C2",
  question: " L'Amanita caesarea si può confondere con:",
  options: ["A. la Clitocybe dealbata", "B. l'Amanita muscaria var. aureola", "C.l'Agaricus arvensis"],
  answer: 1,
  explanation: "B. l'Amanita muscaria var. aureola",
},
{
  id: "C3",
  question: " La Calocybe gambosa può essere scambiata per:",
  options: ["A. Entoloma sinuatum", "B. Russula delica", "C. Marasmius oreades"],
  answer: 0,
  explanation: "A. Entoloma sinuatum",
},
{
  id: "C4",
  question: " L'Armillaria mellea può essere scambiata con:",
  options: ["A. l'Hypholoma fascicolare", "B. l'Amanita verna", "C. l'Amanita virosa"],
  answer: 0,
  explanation: "A. l'Hypholoma fascicolare",
},
{
  id: "C5",
  question: " L'Agaricus arvensis si può confondere con:",
  options: ["A. l'Agaricus xanthoderma", "B. la Russula aurea", "C. il Suillus granulatus"],
  answer: 0,
  explanation: "A. l'Agaricus xanthoderma",
},
{
  id: "C6",
  question: " Il Boletus reticulatus può essere scambiato con:",
  options: ["A. Russula virescens", "B. Lepiota cristata", "C. Tylopilus felleus"],
  answer: 2,
  explanation: "C. Tylopilus felleus",
},
{
  id: "C7",
  question: " Il Cantharellus cibarius può essere scambiato con:",
  options: ["A. Russula aurea", "B. Amanita caersarea", "C. Omphalotus olearius"],
  answer: 2,
  explanation: "C. Omphalotus olearius",
},
{
  id: "C8",
  question: " Il Tricholoma terreum può essere scambiato con:",
  options: ["A. Tricholoma pardinum", "B. Hygrophorus penarius", "C. Pleurotus ostreatus"],
  answer: 0,
  explanation: "A. Tricholoma pardinum",
},
{
  id: "C9",
  question: " La Macrolepiota mastoidea può essere scambiata con:",
  options: ["A. Lepiota clypeolaria", "B. Agaricus arvensis", "C. Marasmius oreades"],
  answer: 0,
  explanation: "A. Lepiota clypeolaria",
},
{
  id: "C10",
  question: "Ramaria formosa può essere scambiata con:",
  options: ["A. Ramaria aurea", "B. Clitocybe geotropa", "C. Armillaria mellea"],
  answer: 0,
  explanation: "A. Ramaria aurea",
},
{
  id: "C11",
  question: "I funghi:",
  options: ["A. sono facilmente digeribili", "B. vanno considerati come alimento complementare e mangiati con moderazione", "C. sono molto nutrienti"],
  answer: 1,
  explanation: "B. vanno considerati come alimento complementare e mangiati con moderazione",
},
{
  id: "C12",
  question: "I funghi contengono in peso fresco:",
  options: ["A. 10% di acqua", "B. 20% acqua", "C. 80-90% di acqua"],
  answer: 2,
  explanation: "C. 80-90% di acqua",
},
{
  id: "C13",
  question: "I funghi:",
  options: ["A. hanno alto valore energetico", "B. hanno scarso valore energetico", "C. sono molto energetici"],
  answer: 1,
  explanation: "B. hanno scarso valore energetico",
},
{
  id: "C14",
  question: "Nei funghi sono presenti:",
  options: ["A. carboidrati e proteine non assimilabili", "B. carboidrati e proteine tutti assimilabili", "C. non sono presenti carboidrati e proteine"],
  answer: 0,
  explanation: "A. carboidrati e proteine non assimilabili",
},
{
  id: "C15",
  question: "La sindrome falloidea:",
  options: ["A. è una sindrome a breve incubazione", "B. è una sindrome a lunga incubazione", "C. non è una sindrome"],
  answer: 1,
  explanation: "B. è una sindrome a lunga incubazione",
},
{
  id: "C16",
  question: "Nella sindrome falloidea le tossine:",
  options: ["A. hanno come organo bersaglio il fegato", "B. hanno come organo bersaglio i reni", "C. hanno come organo bersaglio le cellule muscolari"],
  answer: 0,
  explanation: "A. hanno come organo bersaglio il fegato",
},
{
  id: "C17",
  question: "Il Cortinarius orellanus provoca:",
  options: ["A. sindrome norleucinica", "B. sindrome orellanica", "C. sindrome gastrointestinale"],
  answer: 1,
  explanation: "B. sindrome orellanica",
},
{
  id: "C18",
  question: "La sindrome panterinica è provocata da:",
  options: ["A. Amanita muscaria", "B. Amanita pantherina", "C. Amanita muscaria e pantherina"],
  answer: 2,
  explanation: "C. Amanita muscaria e pantherina",
},
{
  id: "C19",
  question: "Entoloma sinuatum provoca:",
  options: ["A. Sindrome gastrointestinale", "B. Sindrome rabdomiolitica", "C. Sindrome muscarinica"],
  answer: 0,
  explanation: "A. Sindrome gastrointestinale",
},
{
  id: "C20",
  question: "La sindrome gastrointestinale è causata da:",
  options: ["A. Russula cyanoxantha", "B. Amanita caesarea", "C. Omphalotus olearius"],
  answer: 2,
  explanation: "C. Omphalotus olearius",
},
{
  id: "C21",
  question: "Nella sindrome orellanica:",
  options: ["A. si ha danno renale", "B. si ha danno epatico", "C. si hanno allucinazioni"],
  answer: 0,
  explanation: "A. si ha danno renale",
},
{
  id: "C22",
  question: "Il coprinus atramentarius provoca:",
  options: ["A. sindrome gastrointestinale", "B. sindrome coprinica", "C. sindrome muscarinica"],
  answer: 1,
  explanation: "B. sindrome coprinica",
},
{
  id: "C23",
  question: "L'Amanita proxima provoca:",
  options: ["A. porpore emorragiche cutanee", "B. danno renale reversibile", "C. euforia"],
  answer: 1,
  explanation: "B. danno renale reversibile",
},
{
  id: "C24",
  question: "In caso di insorgenza di disturbi dopo il consumo di funghi occorre:",
  options: ["A. rimanere a casa", "B. recarsi al pronto soccorso, portare gli avanzi dei funghi consumati, fornire indicazioni utili al riconoscimento delle specie fungine consumate", "C. prendere dei farmaci analgesici"],
  answer: 1,
  explanation: "B. recarsi al pronto soccorso, portare gli avanzi dei funghi consumati, fornire indicazioni utili al riconoscimento delle specie fungineconsumate",
},
{
  id: "C25",
  question: "Le sindromi a lunga incubazione sono:",
  options: ["A. potenzialmente benigne, tempo di latenza inferiore alle 6 ore, neurotossiche o gastroenteriche", "B. potenzialmente mortali, tempo di latenza superiore a 6 ore, citotossiche per fegato o reni", "C. potenzialmente benigne, tempo di latenza superiore a 6 ore, citotossiche per fegato o reni"],
  answer: 1,
  explanation: "B. potenzialmente mortali, tempo di latenza superiore a 6 ore, citotossiche per fegato o reni",
},
{
  id: "C26",
  question: "In caso di dubbio sulla commestibilità dei funghi:",
  options: ["A bisogna portarli dal Medico di base", "B si devono consultare i libri", "C bisogna portarli ai Micologi delle AST"],
  answer: 2,
  explanation: "C bisogna portarli ai Micologi delle AST",
},
{
  id: "C27",
  question: "L’Ispettore micologo:",
  options: ["A. è una figura specifica prevista dalla legge per il controllo dei funghi", "B. è il nome attribuito a chi studia i funghi", "C. è una funzione svolta dal responsabile della vendita dei funghi"],
  answer: 0,
  explanation: "A. è una figura specifica prevista dalla legge per il controllo dei funghi",
},
{
  id: "C28",
  question: "In caso di sospetta intossicazioni da funghi l’intervento dell’Ispettore Micologo, chiamato dal Pronto Soccorso, si limita a:",
  options: ["A. verificare se l’intossicato è in possesso di idonei documenti per la raccolta dei funghi", "B. fornire consulenza ai Sanitari al fine d’individuare la o le specie fungine coinvolte nell’intossicazione escludendo tra esse la presenza di specie tossiche/velenose mortali", "C. verifica le conoscenze micologiche dell’intossicato"],
  answer: 1,
  explanation: "B. fornire consulenza ai Sanitari al fine d’individuare la o le specie fungine coinvolte nell’intossicazione escludendo tra esse la presenza di specie tossiche/velenose mortali",
},
{
  id: "C29",
  question: "Tra i compiti degli Ispettori Micologi ci sono:",
  options: ["A. il censimento della flora micologica regionale", "B. controllo e certificazione di commestibilità dei funghi freschi spontanei raccolti dai privati cittadini e destinati al consumo diretto", "C. indicare gli ingredienti migliori da utilizzare nella realizzazione di nuove ricette"],
  answer: 1,
  explanation: "B. controllo e certificazione di commestibilità dei funghi freschi spontanei raccolti dai privati cittadini e destinati al consumo diretto",
},
{
  id: "C30",
  question: "Nei confronti delle scuole quale è il ruolo svolto dall’Ispettore Micologo",
  options: ["A. segnalare dove crescono i funghi", "B. svolgere attività educativa ed informativa sia in campo ecologico/ambientale che micologico", "C. indicare gli ingredienti migliori da utilizzare nella realizzazione di nuove ricette"],
  answer: 1,
  explanation: "B. svolgere attività educativa ed informativa sia in campo ecologico/ambientale che micologico",
},
{
  id: "C31",
  question: "I funghi sottoposti al controllo dell’Ispettorato Micologico per il consumo diretto devono essere:",
  options: ["A. puliti e privi di gambo", "B. maturi ed imbibiti d’acqua", "C. sani e in buono stato di conservazione, interi e puliti da terriccio, foglie e/o altri corpi estranei"],
  answer: 2,
  explanation: "C. sani e in buono stato di conservazione, interi e puliti da terriccio, foglie e/o altri corpi estranei",
},
{
  id: "C32",
  question: "All’Ispettorato Micologico cosa deve portare il raccoglitore privato al fine dell’ottenimento della certificazione di commestibilità dei funghi sottoposti a controllo:",
  options: ["A. l’intero quantitativo raccolto", "B. alcune fotografie degli esemplari raccolti e del luogo di raccolta", "C. un solo esemplare per specie"],
  answer: 0,
  explanation: "A. l’intero quantitativo raccolto",
},
{
  id: "C33",
  question: "All’Ispettorato Micologico come vanno consegnati i funghi che vanno sottoposti a visita per l’ottenimento della certificazione di commestibilità:",
  options: ["A. posti all’intero di un contenitore areato e coperti con un telo", "B. riposti alla rinfusa in uno scatolone", "C. posti all’interno di un sacchetto per alimenti di nylon"],
  answer: 0,
  explanation: "A. posti all’intero di un contenitore areato e coperti con un telo",
},
{
  id: "C34",
  question: "Quali sono le operazioni principali che svolge l’Ispettore Micologo in caso di chiamata in seguito di una sospetta intossicazione da funghi:",
  options: ["A. svolge indagini al fine di individuare le persone coinvolti nell’episodio d’intossicazione, visiona l’eventuale materiale fungino (sia crudo che cotto) al fine del riconoscimento delle specie coinvolte, dispone accertamenti microscopici e tossicologici e comunica le, proprie risultanze al personale Sanitario", "B. richiede all’intossicato copia dell’abilitazione alla raccolta (tesserino) e titolo per la raccolta (ricevuta di pagamento) in corso di validità", "C. si informa dell’esatto percorso svolto dal raccoglitore e dal quantitativo di prodotto raccolto"],
  answer: 0,
  explanation: "A. svolge indagini al fine di individuare le persone coinvolti nell’episodio d’intossicazione, visiona l’eventuale materiale fungino (sia crudo che cotto) al fine del riconoscimento delle specie coinvolte, dispone accertamenti microscopici e tossicologici e comunica le, proprie risultanze al personale Sanitario",
},
{
  id: "C35",
  question: "Tra i compiti di vigilanza dell’Ispettorato Micologico vi è quello di:",
  options: ["A. controllare il rispetto del quantitativo di funghi raccolti nel rispetto della Legge Reg.le n.18/2022", "B. verificare che i contenitori in cui sono riposti i funghi siano idonei", "C. controllo e certificazione dei funghi freschi spontanei destinati alla vendita all’ingrosso o al dettaglio presso mercati ortofrutticoli o, altri esercizi e/o alla somministrazione negli esercizi di ristorazione e/o gastronomie"],
  answer: 2,
  explanation: "C. controllo e certificazione dei funghi freschi spontanei destinati alla vendita all’ingrosso o al dettaglio presso mercati ortofrutticoli o, altri esercizi e/o alla somministrazione negli esercizi di ristorazione e/o gastronomie",
},
{
  id: "C36",
  question: "Cosa viene rilasciata a seguito dell’esame di commestibilità dei funghi raccolti dai privati e destinati al consumo diretto:",
  options: ["A. attestazione di avvenuto controllo micologico", "B. il ricettario per corretto consumo dei funghi", "C. certificazione sanitaria di commestibilità dei funghi visionati e controllati"],
  answer: 2,
  explanation: "C. certificazione sanitaria di commestibilità dei funghi visionati e controllati",
},
{
  id: "C37",
  question: "L’Ispettore Micologo deve rifiutare la determinazione della specie quando:",
  options: ["A. i funghi hanno crescita lignicola", "B. sono in evidente stato di alterazione (vecchi, mollicci, liquefatti)", "C. sono cresciuti in ambienti retrodunali"],
  answer: 1,
  explanation: "B. sono in evidente stato di alterazione (vecchi, mollicci, liquefatti)",
},
{
  id: "C38",
  question: "L’Ispettore Micologo deve rifiutare la determinazione della specie quando:",
  options: ["A. i funghi sono tutti con tubuli e pori", "B. i funghi sono stati raccolti nei pascoli montani", "C. sono posti in contenitori non rigidi (sportine plastiche) con conseguente sbriciolamento"],
  answer: 2,
  explanation: "C. sono posti in contenitori non rigidi (sportine plastiche) con conseguente sbriciolamento",
},
{
  id: "C39",
  question: "L’Ispettorato micologico è istituito presso:",
  options: ["A. le Comunità Montane", "B. i Comuni", "C. le Aziende Sanitarie Territoriali"],
  answer: 2,
  explanation: "C. le Aziende Sanitarie Territoriali",
},
{
  id: "C40",
  question: "Dove devono essere portati i funghi raccolti per il controllo della commestibilità:",
  options: ["A. nel comune di residenza", "B. all’Ispettorato Micologico", "C. alla Comunità Montana"],
  answer: 1,
  explanation: "B. all’Ispettorato Micologico",
},
{
  id: "C41",
  question: "Chi controlla la commestibilità dei funghi epigei spontanei:",
  options: ["A. un esperto sanitario", "B. un micologo", "C. un esperto forestale"],
  answer: 1,
  explanation: "B. un micologo",
},
{
  id: "C42",
  question: "Come devono essere portati i funghi all’Ispettorato Micologico:",
  options: ["A. anche spezzati e nel più breve tempo possibile", "B. puliti e tagliati", "C. interi, sani e in buon stato di conservazione"],
  answer: 2,
  explanation: "C. interi, sani e in buon stato di conservazione",
},
{
  id: "C43",
  question: "Il controllo sanitario dei funghi raccolti:",
  options: ["A. è gratuito", "B. si paga solo se il quantitativo supera i 3 kg.", "C. dipende dai generi sottoposti a controllo"],
  answer: 0,
  explanation: "A. è gratuito",
},
{
  id: "C44",
  question: "I funghi contengono in peso fresco:",
  options: ["A. carboidrati 3-5% di cui alcuni non assimilabili come la chitina che costituisce le pareti cellulari dei funghi","B. carboidrati tutti assimilabili","C. non contengono carboidrati"],
  answer: 0,
  explanation: "A. carboidrati 3-5% di cui alcuni non assimilabili come la chitina che costituisce le pareti cellulari dei funghi",
},
{
  id: "C45",
  question: "Le sindromi a breve incubazione sono",
  options: ["A. potenzialmente benigne, tempo di latenza inferiore alle 6 ore, neurotossiche o gastroenteriche","B. potenzialmente mortali, tempo di latenza superiore a 6 ore, citotossiche per fegato o reni","C. potenzialmente benigne, tempo di latenza superiore a 6 ore, citotossiche per fegato o reni"],
  answer: 0,
  explanation: "A. potenzialmente benigne, tempo di latenza inferiore alle 6 ore, neurotossiche o gastroenteriche",
},
{
  id: "C46",
  question: "L’accesso all’Ispettorato Micologico avviene tramite",
  options: ["A. prenotazione al CUP","B. contattando telefonicamente il Dipartimento di Prevenzione e richiedendo gli orari ed i giorni di erogazione del servizio o consultando i canali informatici delle Aziende Sanitarie Territoriali","C. l’invio di apposita domanda per mail"],
  answer: 1,
  explanation: "B. contattando telefonicamente il Dipartimento di Prevenzione e richiedendo gli orari ed i giorni di erogazione del servizio o consultando i canali informatici delle Aziende Sanitarie Territoriali",
},
{
  id: "D1",
  question: " La legge regionale n.18/2022 prevede limiti e divieti per la raccolta dei funghi:",
  options: ["A. non è previsto nessun limite o divieto nella raccolta", "B. sono previsti limiti e divieti ma non ci sono sanzioni a chi non li rispetta", "C. sì, sono previste sanzioni amministrative graduate sulla base della gravità dell’infrazione effettuata"],
  answer: 2,
  explanation: "C. sì, sono previste sanzioni amministrative graduate sulla base della gravità dell’infrazione effettuata",
},
{
  id: "D2",
  question: " Quale è la normativa regionale che Disciplina per la raccolta e la commercializzazione dei funghi epigei spontanei:",
  options: ["A. La legge regionale n.17/2021", "B. La legge regionale n.18/2022", "C. Non è prevista nessuna legge regionale"],
  answer: 1,
  explanation: "B. La legge regionale n.18/2022",
},
{
  id: "D3",
  question: " Le funzioni amministrative in materia di raccolta dei funghi epigei spontanei sono svolte:",
  options: ["A. sono svolte dalle Unioni montane e dalla Regione per il restante territorio per i territori di propria competenza", "B. sono svolte dai comuni", "C. sono svolte dalle province"],
  answer: 0,
  explanation: "A. sono svolte dalle Unioni montane e dalla Regione per il restante territorio per i territori di propria competenza",
},
{
  id: "D4",
  question: " La raccolta dei funghi epigei spontanei è consentita:",
  options: ["A. è consentita ovunque", "B. è consentita nei boschi", "C. è consentita nei boschi e nei terreni non coltivati compatibilmente con le esigenze di salvaguardia, dell'ambiente naturale e degli ecosistemi vegetali, nel rispetto dei limiti e dei divieti"],
  answer: 2,
  explanation: "C. è consentita nei boschi e nei terreni non coltivati compatibilmente con le esigenze di salvaguardia, dell'ambiente naturale e degli ecosistemi vegetali, nel rispetto dei limiti e dei divieti",
},
{
  id: "D5",
  question: " Nelle aree naturali protette del territorio regionale , la raccolta dei funghi epigei spontanei:",
  options: ["A. è consentita nei prati", "B. è consentita nei boschi", "C. è disciplinata dai relativi organismi di gestione"],
  answer: 2,
  explanation: "C. è disciplinata dai relativi organismi di gestione",
},
{
  id: "D6",
  question: " La raccolta dei funghi epigei spontanei può essere esercitata, dall'alba al tramonto, da persone che:",
  options: ["A. abbiano compiuto il sedicesimo anno di età e siano in possesso dell'abilitazione alla raccolta", "B. siano in possesso del titolo per la raccolta", "C. siano in possesso di entrambe le condizioni di cui alle lettere A) e B) precedenti"],
  answer: 2,
  explanation: "C. siano in possesso di entrambe le condizioni di cui alle lettere A) e B) precedenti",
},
{
  id: "D7",
  question: " Possono effettuare la raccolta senza essere muniti del titolo per la raccolta:",
  options: ["A. i minori di anni sedici", "B. i minori di anni sedici, purché accompagnati da persona maggiorenne in possesso dell'abilitazione e, del titolo per la raccolta", "C. i maggiorenni"],
  answer: 1,
  explanation: "B. i minori di anni sedici, purché accompagnati da persona maggiorenne in possesso dell'abilitazione e, del titolo per la raccolta",
},
{
  id: "D8",
  question: " Sono esonerati dal possesso dell'abilitazione alla raccolta:",
  options: ["A. non esistono esonerati dal possesso dell'abilitazione alla, raccolta", "B. coloro che hanno meno di diciotto anni", "C. coloro che sono in possesso dell'attestato di micologo rilasciato ai sensi del decreto ministeriale 29 novembre 1996, n. 686"],
  answer: 2,
  explanation: "C. coloro che sono in possesso dell'attestato di micologo rilasciato ai sensi del decreto ministeriale 29 novembre 1996, n. 686",
},
{
  id: "D9",
  question: "L'abilitazione alla raccolta dei funghi epigei spontanei è rilasciata:",
  options: ["A. dalla Regione e dalle Unioni montane territorialmente competenti", "B. dai comuni montani", "C. solo dalla Regione"],
  answer: 0,
  explanation: "A. dalla Regione e dalle Unioni montane territorialmente competenti",
},
{
  id: "D10",
  question: "Costituisce titolo per la raccolta:",
  options: ["A. la ricevuta di pagamento di euro 20,00 solo per i residenti nei comuni montani", "B. la ricevuta di pagamento di euro 20,00 per i residenti e non residenti nella Regione Marche", "C. la ricevuta di pagamento di euro 40,00"],
  answer: 1,
  explanation: "B. la ricevuta di pagamento di euro 20,00 per i residenti e non residenti nella Regione Marche",
},
{
  id: "D11",
  question: "I residenti in regione provvedono al pagamento dell'importo del titolo per la raccolta:",
  options: ["A. all'Unione montana di riferimento, nel caso in cui il comune di residenza ricada nella stessa", "B. sempre alla Regione Marche", "C. è indifferente"],
  answer: 0,
  explanation: "A. all'Unione montana di riferimento, nel caso in cui il comune di residenza ricada nella stessa",
},
{
  id: "D12",
  question: "I non residenti in regione provvedono al pagamento dell'importo del titolo per la raccolta:",
  options: ["A. sempre alla Regione Marche", "B. alla Regione, nel caso in cui la raccolta sia prevalentemente effettuata nei comuni fuori dalle Unioni montane", "C. è indifferente"],
  answer: 1,
  explanation: "B. alla Regione, nel caso in cui la raccolta sia prevalentemente effettuata nei comuni fuori dalle Unioni montane",
},
{
  id: "D13",
  question: "Oltre al titolo per la raccolta, i non residenti in regione, che effettuano la raccolta nei comuni delle Unioni montane:",
  options: ["A. non devono fare nessun versamento", "B. devono versare una somma da euro 3,00 ad euro 70,00 oltre al titolo per la raccolta", "C. devono versare una somma di euro 20,00 solo per i residenti nei comuni montani"],
  answer: 1,
  explanation: "B. devono versare una somma da euro 3,00 ad euro 70,00 oltre al titolo per la raccolta",
},
{
  id: "D14",
  question: "I carpofori vanno raccolti:",
  options: ["A. con torsione in modo da conservare intatte tutte le caratteristiche morfologiche", "B. con rastrelli", "C. è indifferente come vengono raccolti"],
  answer: 0,
  explanation: "A. con torsione in modo da conservare intatte tutte le caratteristiche morfologiche",
},
{
  id: "D15",
  question: "La quantità massima della raccolta giornaliera per persona è fissata:",
  options: ["A. è fissata in tre chilogrammi", "B. è fissata in quattro chilogrammi", "C. è fissata in cinque chilogrammi"],
  answer: 0,
  explanation: "A. è fissata in tre chilogrammi",
},
{
  id: "D16",
  question: "E' vietata la raccolta dell'amanita caesarea allo stato di ovulo chiuso:",
  options: ["A. no", "B. si sempre", "C. no se di dimensioni notevoli"],
  answer: 1,
  explanation: "B. si sempre",
},
{
  id: "D17",
  question: "E' vietata la raccolta del genere Agaricus, Boletus e Calocybe :",
  options: ["A. no non è vietata", "B. si sempre", "C. è vietata in caso di diametro del cappello inferiore a 3 cm"],
  answer: 2,
  explanation: "C. è vietata in caso di diametro del cappello inferiore a 3 cm",
},
{
  id: "D18",
  question: "Per coloro che esercitano la raccolta senza essere in possesso dell’abilitazione o titolo per la raccolta:",
  options: ["A. si procede alla confisca dei funghi raccolti", "B. si applica una sanzione amministrativa pecuniaria compresa tra euro 250,00 ed euro 500,00", "C. si procede al ritiro dell’abilitazione"],
  answer: 1,
  explanation: "B. si applica una sanzione amministrativa pecuniaria compresa tra euro 250,00 ed euro 500,00",
},
{
  id: "D19",
  question: "La raccolta è vietata:",
  options: ["A. nei boschi", "B. nei terreni in cui non è consentito l'accesso ai sensi dell'articolo 841 del codice civile", "C. nei boschi privati"],
  answer: 1,
  explanation: "B. nei terreni in cui non è consentito l'accesso ai sensi dell'articolo 841 del codice civile",
},
{
  id: "D20",
  question: "E' vietato raccogliere i funghi nelle aree urbane e a verde pubblico:",
  options: ["A. no è sempre consentito", "B. si", "C. solo se non sono boschi"],
  answer: 0,
  explanation: "B. si",
},
{
  id: "D21",
  question: "Coloro che nella raccolta non osservino le norme della legge regionale 18/2022 sono soggetti:",
  options: ["A. alla confisca dei funghi raccolti", "B. a sanzioni amministrative", "C. alla confisca dei funghi raccolti e a sanzioni amministrative"],
  answer: 2,
  explanation: "C. alla confisca dei funghi raccolti e a sanzioni amministrative",
},
{
  id: "D22",
  question: "Per le violazioni delle modalità di raccolta:",
  options: ["A. si procede alla confisca dei funghi raccolti", "B. si applica una sanzione amministrativa compresa tra euro 80,00 ed euro 260,00.", "C. si procede al ritiro del titolo abilitativo"],
  answer: 1,
  explanation: "B. si applica una sanzione amministrativa compresa tra euro 80,00 ed euro 260,00.",
},
{
  id: "D23",
  question: "Per le violazioni per la violazione dei divieti o dei limiti di raccolta di cui all'articolo 8:",
  options: ["A. si procede alla confisca dei funghi raccolti", "B. si applica una sanzione amministrativa compresa tra euro 50,00 ed euro 150,00", "C. si procede al ritiro del titolo abilitativo"],
  answer: 1,
  explanation: "B. si applica una sanzione amministrativa compresa tra euro 50,00 ed euro 150,00",
},
{
  id: "D24",
  question: "Una raccolta indiscriminata di funghi a lungo termine implica:",
  options: ["A. aumento della produzione micologica", "B. favorisce il proliferare di alcune specie", "C. annulla la produzione micologica per lungo tempo"],
  answer: 2,
  explanation: "C. annulla la produzione micologica per lungo tempo",
},
{
  id: "D25",
  question: "Qual è il quantitativo massimo dei funghi che si possono raccogliere in un giorno:",
  options: ["A. kg. 1", "B. kg. 3", "C. non ci sono limiti"],
  answer: 1,
  explanation: "B. kg. 3",
},
{
  id: "D26",
  question: "La raccolta dei funghi è libera:",
  options: ["A. nei boschi e terreni coltivati", "B. nei boschi e terreni non coltivati", "C. ad un’altezza sul livello di 500 metri", "41"],
  answer: 1,
  explanation: "B. nei boschi e terreni non coltivati",
},
{
  id: "D27",
  question: "Per il trasporto dei funghi raccolti si usa:",
  options: ["A. retina traspirante", "B. cestino chiuso di qualsiasi materiale", "C. cestino ben aerato"],
  answer: 2,
  explanation: "C. cestino ben aerato",
},
{
  id: "D28",
  question: "E’ vietato raccogliere funghi:",
  options: ["A. nelle aree urbane a verde pubblico", "B. nei pascoli per bovini e ovini", "C. sui prati perenni"],
  answer: 0,
  explanation: "A. nelle aree urbane a verde pubblico",
},
{
  id: "D29",
  question: "I funghi vanno raccolti:",
  options: ["A. tagliati alla base del gambo", "B. tagliati sotto il cappello", "C. esercitando una torsione alla base del gambo"],
  answer: 2,
  explanation: "C. esercitando una torsione alla base del gambo",
},
{
  id: "D30",
  question: "Dove deve avvenire la sommaria pulizia dei funghi:",
  options: ["A. al ritorno presso la propria abitazione", "B. al primo fontanile trovato", "C. in loco"],
  answer: 2,
  explanation: "C. in loco",
},
{
  id: "D31",
  question: "E’ consentita la raccolta dei funghi in ore notturne:",
  options: ["A. si solo durante l’ora legale", "B. no, mai", "C. solo nel periodo estivo"],
  answer: 1,
  explanation: "B. no, mai",
},
{
  id: "D32",
  question: "La raccolta dei funghi all’interno delle Aziende faunistico venatorie ed agrituristico venatorie è consentita:",
  options: ["A. mai", "B. nei soli giorni di silenzio venatorio", "C. nei giorni feriali"],
  answer: 1,
  explanation: "B. nei soli giorni di silenzio venatorio",
},
{
  id: "D33",
  question: "I funghi dopo la raccolta devono essere riposti e trasportati:",
  options: ["A. in contenitori di plastica", "B. in contenitori rigidi e aerati", "C. è indifferente si possono utilizzare qualsiasi contenitori"],
  answer: 1,
  explanation: "B. in contenitori rigidi e aerati",
},
{
  id: "D34",
  question: "L’uso di uncini e rastrelli per la raccolta dei funghi è consentita:",
  options: ["A. dopo un temporale", "B. in caso di zona infestata da vipere", "C. mai "],
  answer: 2,
  explanation: "C. mai",
},
{
  id: "E1",
  question: " Nella Regione Marche i funghi tossici:",
  options: ["A. non crescono", "B. non hanno mai rappresentato un pericolo per la salute umana", "C. sono comunemente presenti nell’ambiente"],
  answer: 2,
  explanation: "C. sono comunemente presenti nell’ambiente",
},
{
  id: "E2",
  question: " I funghi sono utili al bosco e in che modo:",
  options: ["A. non sono utili, pertanto si possono distruggere", "B. sono utili ma solo quelli commestibili", "C. sì, sono tutti utili, la loro presenza è indice di un bosco in salute"],
  answer: 2,
  explanation: "C. sì, sono tutti utili, la loro presenza è indice di un bosco in salute",
},
{
  id: "E3",
  question: " Un ecosistema boschivo è:",
  options: ["A. è l’insieme di esseri viventi e non viventi che popolano un territorio in equilibrio tra loro", "B. è un bosco privato ecologico", "C. è un bosco integrale interdetto all’uomo"],
  answer: 0,
  explanation: "A. è l’insieme di esseri viventi e non viventi che popolano un territorio in equilibrio tra loro",
},
{
  id: "E4",
  question: " I funghi:",
  options: ["A. contengono clorofilla", "B. non contengono clorofilla", "C. hanno tutti l’anello"],
  answer: 0,
  explanation: "B. non contengono clorofilla",
},
{
  id: "E5",
  question: " I funghi appartengono:",
  options: ["A. al regno vegetale", "B. al regno animale", "C. ad un regno a sé stante"],
  answer: 2,
  explanation: "C. ad un regno a sé stante",
},
{
  id: "E6",
  question: " E’ prevista la vigilanza sul rispetto delle norme della legge regionale 18/2022 :",
  options: ["A. no non è prevista", "B. si è prevista solo d parte degli enti competenti", "C. si è prevista ed è esercitata dai soggetti di cui all'articolo 11 del d.p.r. 376/1995"],
  answer: 2,
  explanation: "C. si è prevista ed è esercitata dai soggetti di cui all'articolo 11 del d.p.r. 376/1995",
},
{
  id: "E7",
  question: " La raccolta dei funghi epigei spontanei nelle aree naturali protette del territorio regionale:",
  options: ["A. è sempre possibile", "B. è disciplinata dai relativi organismi di gestione", "C. è sempre vietata"],
  answer: 1,
  explanation: "B. è disciplinata dai relativi organismi di gestione",
},
{
  id: "E8",
  question: " La raccolta funghi all'interno delle Aziende faunistico venatorie ed agrituristico venatorie:",
  options: ["A. è sempre", "consentita", "B. è consentita nei giorni di silenzio venatorio", "C. no non è consentita"],
  answer: 1,
  explanation: "B. è consentita nei giorni di silenzio venatorio",
},
{
  id: "E9",
  question: "I funghi:",
  options: ["A. si autoalimentano come le piante", "B. non sono in grado di costruirsi le sostanze nutritizie", "C. vivono negli ambienti acquatici"],
  answer: 1,
  explanation: "B. non sono in grado di costruirsi le sostanze nutritizie",
},
{
  id: "E10",
  question: "I funghi si riproducono:",
  options: ["A. per mezzo di semi chiamati “spore”", "B. solo a luna calante", "C. per duplicazione come i batteri"],
  answer: 0,
  explanation: "A. per mezzo di semi chiamati “spore”",
},
{
  id: "E11",
  question: "Cos’è un bosco:",
  options: ["A. un insieme di alberi", "B. un ecosistema caratterizzato da vegetazione arborea permanente", "C. ovunque si possa tagliare legna dopo essere stati autorizzati"],
  answer: 1,
  explanation: "B. un ecosistema caratterizzato da vegetazione arborea permanente",
},
{
  id: "E12",
  question: "Che cos’è un prato perenne:",
  options: ["A. un ecosistema caratterizzato da vegetazione erbacea", "B. un prato molto grande che si sfalcia", "C. un pascolo per bovini"],
  answer: 0,
  explanation: "A. un ecosistema caratterizzato da vegetazione erbacea",
},
{
  id: "E13",
  question: "Nella raccolta dei funghi è vietato l'uso di rastrelli:",
  options: ["A. no è permesso", "B. no è permesso solo nei giardini", "C. si per non danneggiare lo strato umifero del terreno"],
  answer: 2,
  explanation: "C. si per non danneggiare lo strato umifero del terreno",
},

    // Add more questions here... testetstes
];
    var totalQuestions = questions.length;
    // Function to shuffle an array using the Fisher-Yates algorithm
    function shuffleArray(array) {
      for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
      }
    }

    // Shuffle the questions array to randomize the order
    shuffleArray(questions);

    var currentQuestionIndex = 0;
    var correctResponses = 0;
    var incorrectResponses = 0;

    var totalQuestionsElement = document.getElementById("total-questions");

    var questionContainer = document.getElementById("question-container");
    var questionElement = document.getElementById("question");
    var optionsElement = document.getElementById("options");
    var submitButton = document.getElementById("submit-btn");

    var feedbackContainer = document.getElementById("feedback-container");
    var feedbackElement = document.getElementById("feedback");
    var explanationElement = document.getElementById("explanation");
    var nextButton = document.getElementById("next-btn");

    var scoreContainer = document.getElementById("score-container");
    var correctResponsesElement = document.getElementById("correct-responses");
    var incorrectResponsesElement = document.getElementById("incorrect-responses");

    function displayQuestion(question) {
      questionElement.textContent = question.question;
      totalQuestionsElement.textContent = totalQuestions;
      optionsElement.innerHTML = "";
      for (var i = 0; i < question.options.length; i++) {
        var li = document.createElement("li");
        var input = document.createElement("input");
        input.type = "radio";
        input.name = "option";
        input.value = i;
        li.appendChild(input);
        li.appendChild(document.createTextNode(question.options[i]));
        optionsElement.appendChild(li);
      }
    }

    function validateAnswer(selectedAnswer, correctAnswer) {
      selectedAnswer = parseInt(selectedAnswer); // Parse selected answer as an integer
      if (selectedAnswer === correctAnswer) {
        correctResponses++;
        feedbackElement.textContent = "Corretto!";
        feedbackElement.style.color = "green";
        explanationElement.textContent = "";
        return true;
      } else {
        incorrectResponses++;
        feedbackElement.textContent = "Sbagliato!";
        feedbackElement.style.color = "red";
        explanationElement.textContent = "Risposta esatta: " + questions[currentQuestionIndex].explanation;
        return false;
      }
    }

    function updateScore() {
      correctResponsesElement.textContent = "Corretto: " + correctResponses;
      incorrectResponsesElement.textContent = "Sbagliato: " + incorrectResponses;
    }

    function showFeedback() {
      questionContainer.style.display = "none";
      feedbackContainer.style.display = "block";
      updateScore();
    }

    function showNextQuestion() {
      currentQuestionIndex++;
      if (currentQuestionIndex < questions.length) {
        displayQuestion(questions[currentQuestionIndex]);
        questionContainer.style.display = "block";
        feedbackContainer.style.display = "none";
      } else {
        // All questions answered
        questionContainer.style.display = "none";
        feedbackContainer.style.display = "none";
        scoreContainer.style.display = "block";
      }
    }

    submitButton.addEventListener("click", function() {
      var selectedAnswer = document.querySelector('input[name="option"]:checked').value;
      var isCorrect = validateAnswer(selectedAnswer, questions[currentQuestionIndex].answer);
      showFeedback();
    });

    nextButton.addEventListener("click", function() {
      showNextQuestion();
    });

    displayQuestion(questions[currentQuestionIndex]);